language: ruby
rvm:
  - "2.1.0"
  - "2.2.0"
before_install: gem install bundler --version '~> 1.10.0'
addons:
  postgresql: "9.3"
services:
  - elasticsearch
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - sleep 10
