language: ruby
rvm:
- 2.2
- 2.1
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_ci_test
- psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_ci_test
- rake searchkick:reindex:all
sudo: false
services:
  - elasticsearch
env:
  - ELASTICSEARCH_HOST=localhost
