language: ruby
rvm:
- 2.3.0
- 2.2
- 2.1
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
script:
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rake db:test:prepare RAILS_ENV=test
- bundle exec rake db:fixtures:load RAILS_ENV=test
- bundle exec rake searchkick:reindex:all RAILS_ENV=test
- bundle exec rake test RAILS_ENV=test
sudo: false
services:
- elasticsearch
env:
- ELASTICSEARCH_HOST=localhost RAILS_ENV=test
notifications:
  slack:
    secure: f12r6JgPOSZaVgpMMQdpU6JF8PV9WJRtv5PGyatpFnBL8ZJey53Rr+B+mmChr9R301x9GhqgY+rLjQk8SKtjQJLYNZQJUhBomc+BsXbK/rGJCAgxwbgOJNffQKMh/EFa+w0jKU9t4zWZRr7wlvMKki5XSAiZezFPvlswGbE3CM4=
