production:
  secret_key_base: {{cfg.secret_key_base}}
  elasticsearch_host: {{cfg.elasticsearch_host}}
  glynx2_api: {{cfg.glynx2_api}}
  gina_analytics: {{cfg.gina_analytics}}
  glynx_storage_path: {{cfg.glynx_storage_path}}
