development:
  adapter: postgis
  database: glynx_development
  username: glynx
  password: fj329rghDDw02jf
  schema_search_path: public
  host: 192.168.222.225
  client_encoding: UTF8
test:
  adapter: postgis
  database: glynx_test
  username: glynx
  password: fj329rghDDw02jf
  schema_search_path: public
  host: 192.168.222.225
  client_encoding: UTF8
